#define LARGEUR_FENETRE 1500
#define HAUTEUR_FENETRE 900
#define RAYON_CERCLE 40
#define ABSCISSE_RACINE LARGEUR_FENETRE/2
#define ORDONNEE_RACINE HAUTEUR_FENETRE/2
#define DX_ENTRE_PERE_FILS
#define DY_ENTRE_PERE_FILS

SDL_Surface *ecran=NULL;
